version: "3.7"

x-build-args: &build_args
  PLUGIN_VERSION: ${PLUGIN_VERSION}
  BUILD_DATE: ${BUILD_DATE:-BUILD_DATE_NOT_SET}
  CENTOS_VERSION: 8

services:
  sonarscanner:
    image: sonarscannerbuildkite/sonarscanner:${IMAGE_VERSION:-latest}
    build:
      dockerfile: docker/sonarscanner.dockerfile
      context: .
      args:
        <<: *build_args
        SONAR_SCANNER_VERSION: 4.2.0.1873

  sonarscanner-dotnet:
    image: sonarscannerbuildkite/sonarscanner-dotnet:${IMAGE_VERSION:-latest}
    build:
      dockerfile: docker/sonarscanner-dotnet.dockerfile
      context: .
      args:
        <<: *build_args
        DOTNET2_IMAGE_TAG: 2.2
        DOTNET3_IMAGE_TAG: 3.0

  lint:
    image: sonarscannerbuildkite/sonarscanner-lint
    command: "--format"
    build:
      dockerfile: docker/lint.dockerfile
      context: .
      args:
        GOLANG_VERSION: 1.13.4
    volumes:
      - ".:/app"

  plugin-test:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"

  plugin-lint:
    image: buildkite/plugin-linter
    command:
      [
        "--id=ssh://git@github.com/wayfair-contribs/sonarscanner-buildkite-plugin.git",
      ]
    volumes:
      - ".:/plugin:ro"
