name: "Lint"
on: [push]

jobs:
  plugin-lint:
    name: Buildkite Plugin Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - run: docker-compose run --rm plugin-lint
  lint:
    name: Lint bash and markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - run: docker-compose run --rm lint --check
