name: "Lint"
on:
  push:
    tags-ignore:
      - "*"

jobs:
  plugin-lint:
    name: Buildkite Plugin Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout
      - run: docker-compose run --rm plugin-lint
  lint:
    name: Lint bash and markdown
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout
      - run: docker-compose run --rm lint --check
