name: "Unit Tests"
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Buildkite Plugin Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose run --rm plugin-test
