name: "Unit Tests"
on: [push]

jobs:
  test:
    name: Buildkite Plugin Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - run: docker-compose run --rm plugin-test
