name: "Unit Tests"
on:
  push:
    tags-ignore:
    - '*'

jobs:
  test:
    name: Buildkite Plugin Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout
      - run: docker-compose run --rm plugin-test
